spring.datasource:
  url: ${JDBC_DATABASE_URL}
  driverClassName: org.postgresql.Driver
  maxActive: 10
  maxIdle: 5
  minIdle: 2
  initialSize: 5
  removeAbandoned: true

spring.jpa.generate-ddl: true
hibernate.hbm2dll.auto: create-drop
spring.thymeleaf.cache: false


#logging.level.org.hibernate: DEBUG